pipeline{
    agent any
    tools{
        maven 'maven3'
    }
    stages{
       stage('GetCode'){
            steps{
                    git branch: 'master', url: 'https://github.com/chintucool/SonarQubeMaven.git'
                    echo "branch name - " + env.branch
            }
        }
       stage('SonarQube analysis') {
            when {
                    branch 'master'
            }
            steps{
                    sh 'java -version'
                    sh 'mvn -f sonarqube/pom.xml clean verify package sonar:sonar'
             }
        }
        stage('Jacoco coverage') {
            steps {
                jacoco(
                        execPattern: '**/jacoco.exec',
                        classPattern: '**/classes',
                        sourcePattern: '**/src/main/java',
                        inclusionPattern: '**/*.java'
                )
            }
        }         
       
    }
}
