pipeline{
    agent any
    environment {
        PATH = "$PATH:/usr/local/Cellar/maven/3.8.4/libexec/bin"
    }
    stages{
       stage('GetCode'){
            steps{
                git 'https://github.com/chintucool/javaloginapp.git'
            }
        }
       stage('SonarQube analysis') {
            when {
                branch 'master' 
            }
            steps {
                withSonarQubeEnv('sonar') {
                    sh 'mvn clean package sonar:sonar'
                }
            }
        }
        stage('Jacoco coverage') {
            when {
                branch 'master' 
            }
            steps {
                jacoco(
                        execPattern: '**/jacoco.exec',
                        classPattern: '**/classes',
                        sourcePattern: '**/src/main/java',
                        inclusionPattern: '**/*.java'
                )
            }
        }         
       
    }
}
